name: Awesome CI Workflow

on: [push, pull_request]

jobs:
  MainSequence:
    name: cpp-linter
    runs-on: ubuntu-latest
    steps:
      - name: cpp-linter
        uses: ArtificialAmateur/clang-tidy-action@master
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  build:
    runs-on: ${{ matrix.os }}
    needs: [MainSequence]
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE && make

    - name: Testing Operators
      working-directory: ${{runner.workspace}}/build/tests/operators
      shell: bash
      run: ctest

    - name: Testing Operations
      working-directory: ${{runner.workspace}}/build/tests/operations
      shell: bash
      run: ctest
