name: Awesome CI Workflow

on: [push, pull_request]

jobs:
  MainSequence:
    name: Code Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - name: requirements
        run: | 
          sudo apt -qq -y update
          sudo apt -qq install clang-tidy-10 clang-format-10
          
      - name: Code linter (clang-tidy, clang-format, and cppcheck)
        # You may pin to the exact commit or the version.
        # uses: ArtificialAmateur/cpp-linter-action@6281cc1ef3abe25ee492f19f7d8b184ca873db34
        uses: ArtificialAmateur/cpp-linter-action@0.01
        env: 
          LINTER_TOKEN: ${{ secrets.LINTER_TOKEN }} 

  build:
    runs-on: ${{ matrix.os }}
    needs: [MainSequence]
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE && make

    - name: Testing Operators
      working-directory: ${{runner.workspace}}/build/tests/operators
      shell: bash
      run: ctest

    - name: Testing Operations
      working-directory: ${{runner.workspace}}/build/tests/operations
      shell: bash
      run: ctest
